<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\ScoringCriterion;
use Illuminate\Database\Seeder;

class ScoringCriteriaSeeder extends Seeder
{
    public function run(): void
    {
        $criteria = [
            [
                'name' => 'TAM',
                'description' => 'Total addressable market size',
                'input_type' => 'number',
                'min_value' => 0,
                'max_value' => 100000000,
                'weight' => 1.50,
                'thresholds' => ['min' => 100000, 'target' => 1000000],
                'is_stop_factor' => false,
                'stage' => 'primary',
                'order' => 1,
            ],
            [
                'name' => 'SOM',
                'description' => 'Serviceable obtainable market size',
                'input_type' => 'number',
                'min_value' => 0,
                'max_value' => 10000000,
                'weight' => 1.50,
                'thresholds' => ['min' => 50000, 'target' => 300000],
                'is_stop_factor' => false,
                'stage' => 'primary',
                'order' => 2,
            ],
            [
                'name' => 'Market potential',
                'description' => 'Potential market growth and opportunity',
                'input_type' => 'slider',
                'min_value' => 1,
                'max_value' => 5,
                'weight' => 1.20,
                'thresholds' => null,
                'is_stop_factor' => false,
                'stage' => 'primary',
                'order' => 3,
            ],
            [
                'name' => 'SMG competence fit',
                'description' => 'How well hypothesis matches SMG competencies',
                'input_type' => 'slider',
                'min_value' => 1,
                'max_value' => 5,
                'weight' => 1.10,
                'thresholds' => null,
                'is_stop_factor' => false,
                'stage' => 'primary',
                'order' => 4,
            ],
            [
                'name' => 'Resource intensity',
                'description' => 'Expected resource consumption',
                'input_type' => 'slider',
                'min_value' => 1,
                'max_value' => 5,
                'weight' => 1.00,
                'thresholds' => null,
                'is_stop_factor' => false,
                'stage' => 'primary',
                'order' => 5,
            ],
            [
                'name' => 'Strategic fit',
                'description' => 'Alignment with strategic priorities',
                'input_type' => 'slider',
                'min_value' => 1,
                'max_value' => 5,
                'weight' => 1.20,
                'thresholds' => null,
                'is_stop_factor' => false,
                'stage' => 'primary',
                'order' => 6,
            ],
            [
                'name' => 'Stop factors',
                'description' => 'Critical blockers that stop execution',
                'input_type' => 'checkbox',
                'min_value' => 0,
                'max_value' => 1,
                'weight' => 1.00,
                'thresholds' => null,
                'is_stop_factor' => true,
                'stage' => 'primary',
                'order' => 7,
            ],
            [
                'name' => 'Unit economics',
                'description' => 'Expected unit economics quality',
                'input_type' => 'slider',
                'min_value' => 1,
                'max_value' => 5,
                'weight' => 1.50,
                'thresholds' => null,
                'is_stop_factor' => false,
                'stage' => 'deep',
                'order' => 1,
            ],
            [
                'name' => 'Technical feasibility',
                'description' => 'Technical complexity and feasibility',
                'input_type' => 'slider',
                'min_value' => 1,
                'max_value' => 5,
                'weight' => 1.40,
                'thresholds' => null,
                'is_stop_factor' => false,
                'stage' => 'deep',
                'order' => 2,
            ],
            [
                'name' => 'MVP resources',
                'description' => 'Estimated resource usage for MVP',
                'input_type' => 'number',
                'min_value' => 0,
                'max_value' => 10000,
                'weight' => 1.20,
                'thresholds' => ['min' => 50, 'target' => 500],
                'is_stop_factor' => false,
                'stage' => 'deep',
                'order' => 3,
            ],
            [
                'name' => 'TAM',
                'description' => 'Total addressable market size',
                'input_type' => 'number',
                'min_value' => 0,
                'max_value' => 100000000,
                'weight' => 1.20,
                'thresholds' => ['min' => 100000, 'target' => 1000000],
                'is_stop_factor' => false,
                'stage' => 'deep',
                'order' => 4,
            ],
            [
                'name' => 'SOM',
                'description' => 'Serviceable obtainable market size',
                'input_type' => 'number',
                'min_value' => 0,
                'max_value' => 10000000,
                'weight' => 1.20,
                'thresholds' => ['min' => 50000, 'target' => 300000],
                'is_stop_factor' => false,
                'stage' => 'deep',
                'order' => 5,
            ],
            [
                'name' => 'Market potential',
                'description' => 'Potential market growth and opportunity',
                'input_type' => 'slider',
                'min_value' => 1,
                'max_value' => 5,
                'weight' => 1.10,
                'thresholds' => null,
                'is_stop_factor' => false,
                'stage' => 'deep',
                'order' => 6,
            ],
            [
                'name' => 'SMG competence fit',
                'description' => 'How well hypothesis matches SMG competencies',
                'input_type' => 'slider',
                'min_value' => 1,
                'max_value' => 5,
                'weight' => 1.10,
                'thresholds' => null,
                'is_stop_factor' => false,
                'stage' => 'deep',
                'order' => 7,
            ],
            [
                'name' => 'Resource intensity',
                'description' => 'Expected resource consumption',
                'input_type' => 'slider',
                'min_value' => 1,
                'max_value' => 5,
                'weight' => 1.00,
                'thresholds' => null,
                'is_stop_factor' => false,
                'stage' => 'deep',
                'order' => 8,
            ],
            [
                'name' => 'Strategic fit',
                'description' => 'Alignment with strategic priorities',
                'input_type' => 'slider',
                'min_value' => 1,
                'max_value' => 5,
                'weight' => 1.10,
                'thresholds' => null,
                'is_stop_factor' => false,
                'stage' => 'deep',
                'order' => 9,
            ],
        ];

        foreach ($criteria as $criterion) {
            ScoringCriterion::query()->updateOrCreate(
                [
                    'name' => $criterion['name'],
                    'stage' => $criterion['stage'],
                ],
                [
                    'description' => $criterion['description'],
                    'input_type' => $criterion['input_type'],
                    'min_value' => $criterion['min_value'],
                    'max_value' => $criterion['max_value'],
                    'weight' => $criterion['weight'],
                    'is_active' => true,
                    'thresholds' => $criterion['thresholds'],
                    'is_stop_factor' => $criterion['is_stop_factor'],
                    'order' => $criterion['order'],
                ],
            );
        }
    }
}
